[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/proxy/dynmap"
  to = "http://dynmap.ageofelysian.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
